//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSSUploadTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsValue
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Variables { get; set; }
        public string Value { get; set; }
        public string Labels { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
