//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSSUploadTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectVariable
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string Variables { get; set; }
        public string Typs { get; set; }
        public Nullable<int> UID { get; set; }
        public string Labels { get; set; }
        public string TblName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IsInt { get; set; }
        public string Measure { get; set; }
    }
}
