//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPSSUploadTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectName
    {
        public int Id { get; set; }
        public string ProjectName1 { get; set; }
        public Nullable<int> Processed { get; set; }
    }
}
